timeout 1
default MyOS
menu title Boot the OS

label MyOS
	kernel /vmlinuz-6.17.8-msm8937
	fdt /dtbs/6.17.8-msm8937/qcom/msm8937-xiaomi-land.dtb
	initrd /initrd.img-6.17.8-msm8937
	append console=tty0 root=PARTUUID=8ca60c57-5eb2-1d44-4488-9fbffad1e061 rw loglevel=3 splash
