timeout 1
default MyOS
menu title Boot the OS

label MyOS
	kernel /vmlinuz-6.19.5-msm8937
	fdt /dtbs/6.19.5-msm8937/qcom/msm8937-xiaomi-land.dtb
	initrd /initrd.img-6.19.5-msm8937
	append console=tty0 root=UUID=86c05746-759e-4d3e-98c1-7eded328b685 rw loglevel=3 splash
